# Generated by Django 4.2.7 on 2023-11-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_post_forum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="forum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="main.forum",
            ),
        ),
    ]
