# Generated by Django 4.2.7 on 2023-12-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_forum_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="user",
        ),
    ]
