# Generated by Django 4.2.7 on 2023-12-18 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_created",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 17, 15, 21, 14, 212148, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
