# Generated by Django 4.2.7 on 2023-12-18 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_post_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 18, 15, 23, 43, 149620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
