# Generated by Django 4.2.7 on 2023-12-18 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_post_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
