# Generated by Django 4.2.7 on 2023-12-27 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
